# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: brew2ansible
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: brew2ansible
    goos:
      - linux
      - freebsd
      - openbsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
      - ppc64le
    goarm:
      - 6
      - 7
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

brews:
  - goarm: 6
    tap:
      owner: jufabeck2202
      name: homebrew-formulas
    commit_author:
      name: "Julian Beck"
      email: "ju-fa-beck@t-online.de"
    homepage: "https://juli.sh"
    folder: Formula
    description: "Tool to helps you manage your brew and cask installs using ansible"

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
